# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4123

trigger:
- master

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build job
    pool:
      name: Default
    steps:
    - script: | 
        echo Hello, world !! 
        echo Replace me with your build steps !!
      displayName: 'Build'
    - powershell: Write-Host "Run unit tests for your application..."        
      displayName: 'Unit Testing'

- stage: Deploy
  jobs:
  - deployment: DeployJob
    displayName: Deploy Job-1
    pool:
      name: Default
    environment: staging
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello





    

